config/routes.rb
Portfolio::Application.routes.draw do

  resources :messages, only: [:new, :create]

  resources :projects do
    resources :photos
  end

  get '/testimonials', to: 'testimonials#index'

  devise_for :users

  root :to => 'home#home'

end

app/models/project.rb
require 'mime/types'

class Project < ActiveRecord::Base
  has_attached_file :photo, :styles => { :full => "500x375>", :thumb => "300x225>" }
  has_attached_file :mp3

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.sort_by!{|x| x.updated_at }.reverse
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    authorize @project
  end

  # GET /projects/1/edit
  def edit
    authorize @project
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.create(project_params)
    authorize @project

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    authorize @project

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    authorize @project

    @project.photo = nil
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :technologies_used, :body, :link, :subheading)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :multipart => true } do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subheading %><br>
    <%= f.text_field :subheading %>
  </div>
  <div class="field">
    <%= f.label :technologies_used %><br>
    <%= f.text_area :technologies_used, :cols => "40", :rows => "10" %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :cols => "40", :rows => "10" %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <br>
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1><br>

<div class="project_index">
  <% @projects.each do |project| %>
    <div class="project_container" id="<%= dom_id(project) %>">
      <div class="project_pic">
        <% if project.photos.any? %>
          <%= link_to image_tag(project.photos.first.photo.url(:full)), project %><br>
        <% end %>
      </div>
      <div class="project_text">
        <p id="project_name"><%= project.title %></p>
        <p id="project_subheading"><%= project.subheading %></p>
        <p><%= link_to 'View It!', project %>
        <% if policy(project).edit? %>
          <%= link_to 'Edit', edit_project_path(project) %>
          <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<br>

<div id="new_project">
  <% if policy(Project).create? %>
    <%= link_to 'New Project', new_project_path %>
  <% end %>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h2><%= @project.title %></h2><br>

<div id="project_text">
  <p>
    <strong>Technologies Used</strong><br>
    <%= @project.technologies_used %>
  </p>

  <p>
    <strong>About this Project</strong><br>
    <%= simple_format @project.body %>
  </p>

  <p>
    <strong><%= link_to "Link to Project", "http://#{@project.link}" %></strong>
  </p><br>
</div>

<div id="carousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% @project.photos.each_with_index do |photo, index| %>
      <% if index == 0 %>
        <li data-target="#carousel-example-generic" data-slide-to="<%= index %>" class="active"></li>
      <% else %>
        <li data-target="#carousel-example-generic" data-slide-to="<%= index %>"></li>
      <% end %>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <% @project.photos.each_with_index do |photo, index| %>
      <% if index == 0 %>
        <div class="item active">
          <%= image_tag photo.photo.url(:full) %>
        </div>
      <% else %>
        <div class="item">
          <%= image_tag photo.photo.url(:full) %>
        </div>
      <% end %>
    <% end %>
  </div>

  <!-- Controls -->
  <% if @project.photos.count > 1 %>
    <a class="left carousel-control" href="#carousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  <% end %>

</div>

<div id="project_controls">
  <% if policy(@project).update? %>
    <%= link_to 'Add Photo', new_project_photo_path(@project) %> |
    <%= link_to 'Edit', edit_project_path(@project) %> |
  <% end %>
  <%= link_to 'Back', projects_path %>
</div>