config/routes.rb
Portfolio::Application.routes.draw do

  resources :messages, only: [:new, :create]

  resources :projects do
    resources :photos
  end

  get '/testimonials', to: 'testimonials#index'

  devise_for :users

  root :to => 'home#home'

end

app/views/layouts/_header.html.erb
<head>
  <title><%= "Nicholas Case's Portfolio" %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Nicholas Case</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <% if false %>
              <li><%= link_to 'Blog', blogs_path %></li>
            <% end %>
            <li><%= link_to 'Projects', projects_path %></li>
            <li><%= link_to 'GitHub Profile', "https://github.com/SupahNickie" %></li>
            <li><%= link_to 'LinkedIn', "http://linkedin.com/in/casenicholas" %></li>
            <li><%= link_to 'Resume', "https://drive.google.com/file/d/0B4kmveOI_IiUamlrQXRDNWtELWc/edit?usp=sharing" %></li>
            <li><%= link_to 'Testimonials', testimonials_path %></li>
            <li><%= link_to 'Contact Me', new_message_path(@message) %></li>
            <% if current_user && (Rails.env == "development") %>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <% elsif current_user.nil? && (Rails.env == "development") %>
              <li><%= link_to 'Admin Signin', new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<%= render 'layouts/header' %>

<body class="<%= @seattle ? 'seattle' : ''%>">

<%= render 'layouts/nav' %>

<div class="container" %>
<% flash.each do |key, value| %>
  <h4><%= value %></h4>
<% end %>
  <%= yield %>
</div>

</body>
</html>